@startuml
class AireAcondicionado {
  - temperatura: float
  - encendido: bool
  + __init__()
  + encender()
  + apagar()
  + obtener_estado(): str
  + cambiar_temperatura(nueva_temperatura: float): bool
  + __str__(): str
}
@enduml
